version: '3.9'

networks:
  chat_network:

services:
  postgres:
    image: postgres:15
    container_name: chat_postgres
    restart: always
    networks:
      - chat_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ChatDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: chat_redis
    restart: always
    networks:
      - chat_network
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    depends_on:
      - postgres

  chat-api:
    build: ./chat-api
    container_name: chat_api
    restart: always
    depends_on:
      - postgres
      - redis
      - centrifugo
    networks:
      - chat_network
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ChatDB;Username=postgres;Password=postgres

  chat-frontend:
    build: ./chat-frontend
    container_name: chat_frontend
    restart: always
    networks:
      - chat_network
    ports:
      - "3000:80"

  centrifugo:
    image: centrifugo/centrifugo
    container_name: chat_centrifugo
    restart: always
    networks:
      - chat_network
    volumes:
      - ./centrifugo/config.json:/centrifugo/config.json
    command: centrifugo --config=/centrifugo/config.json
    ports:
      - "8000:8000"
    depends_on:
      - redis

volumes:
  pgdata:
